apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey-instances
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/santidesp/mik8s.git'
    targetRevision: HEAD
    path: infrastructure/instances/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true