apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xredis.database.example.org
spec:
  group: database.example.org
  names:
    kind: XRedis
    plural: xredis
  claimNames:
    kind: RedisClaim
    plural: redisclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              storageGB:
                type: integer
